version: "3.9"
services:
  master:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.master
    environment:
      DB_URL: sqlite:///./transcode.db
    volumes:
      - ../data/in:/app/data/in
      - ../data/out:/app/data/out

  worker:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.worker
    environment:
      DB_URL: sqlite:///./transcode.db
      WORKER_WORKER_ID: worker-1
    volumes:
      - ../data/in:/app/data/in
      - ../data/out:/app/data/out
